/**
 * WidgetRegistry — Source unique de vérité pour tous les widgets OEI.
 *
 * Utilisé par :
 *   - ConceptPage (pages de cours) : montage des widgets dans le contenu JSON
 *   - slides-core.js (viewer Reveal.js) : mountWidgets() lit OEI_WIDGET_REGISTRY
 *   - slides-editor.js (éditeur) : WIDGET_OPTIONS dérivé dynamiquement
 *
 * Champs par entrée :
 *   global      — nom de la classe sur `window`
 *   script      — chemin relatif à shared/components/
 *   label       — nom affiché dans l'éditeur
 *   category    — catégorie de regroupement
 *   description — courte description (tooltip / modale)
 *   level       — niveau pédagogique cible : 'L1', 'L2', 'L3', ou ''
 *   tags        — mots-clés pour la recherche
 *   defaultConfig — config JSON par défaut lors de l'insertion
 *   staticFallback — fn(config) → HTML pour exports raster (PDF/PNG)
 */

// Helper pour le staticFallback standard
const _sf = (icon, name) =>
    () => `<div class="sl-widget-static"><div class="sl-widget-static-icon">${icon}</div><div class="sl-widget-static-name">${name}</div><div class="sl-widget-static-desc">Simulation interactive — disponible en présentation</div></div>`;

const OEI_WIDGET_REGISTRY = {

    // ── DOM / Événements ──────────────────────────────────────────────────────
    'dom-visualizer': {
        global: 'DomTreeWidget',
        script: 'web/DomTreeWidget.js',
        label: 'DOM Visualizer',
        category: 'Web',
        description: 'Visualisation interactive de l\'arbre DOM avec mise en évidence des nœuds',
        level: 'L1',
        tags: ['dom', 'html', 'arbre', 'web'],
        defaultConfig: {},
        staticFallback: _sf('🌳', 'DOM Visualizer'),
    },
    'events-flow-lab': {
        global: 'EventWidgets',
        script: 'web/EventWidgets.js',
        label: 'Lab événements',
        category: 'Web',
        description: 'Laboratoire interactif sur le flux des événements JavaScript',
        level: 'L1',
        tags: ['events', 'javascript', 'web'],
        defaultConfig: { type: 'events-flow-lab' },
        staticFallback: _sf('⚡', 'Lab événements'),
    },
    'events-eventloop-restaurant': {
        global: 'EventWidgets',
        script: 'web/EventWidgets.js',
        label: 'Event loop (restaurant)',
        category: 'Web',
        description: 'Analogie restaurant pour comprendre la boucle d\'événements',
        level: 'L1',
        tags: ['event loop', 'async', 'javascript', 'web'],
        defaultConfig: { type: 'events-eventloop-restaurant' },
        staticFallback: _sf('🍽️', 'Event loop'),
    },
    'events-delegation-standardiste': {
        global: 'EventWidgets',
        script: 'web/EventWidgets.js',
        label: 'Délégation (standardiste)',
        category: 'Web',
        description: 'Analogie standardiste pour la délégation d\'événements',
        level: 'L1',
        tags: ['delegation', 'events', 'javascript', 'web'],
        defaultConfig: { type: 'events-delegation-standardiste' },
        staticFallback: _sf('📞', 'Délégation standardiste'),
    },
    'events-multi-listeners': {
        global: 'EventWidgets',
        script: 'web/EventWidgets.js',
        label: 'Multi-listeners',
        category: 'Web',
        description: 'Démonstration de plusieurs écouteurs sur un même événement',
        level: 'L1',
        tags: ['listeners', 'events', 'javascript', 'web'],
        defaultConfig: { type: 'events-multi-listeners' },
        staticFallback: _sf('👂', 'Multi-listeners'),
    },
    'events-event-object': {
        global: 'EventWidgets',
        script: 'web/EventWidgets.js',
        label: 'Objet événement',
        category: 'Web',
        description: 'Exploration de l\'objet Event et ses propriétés',
        level: 'L1',
        tags: ['event object', 'target', 'javascript', 'web'],
        defaultConfig: { type: 'events-event-object' },
        staticFallback: _sf('📋', 'Objet événement'),
    },
    'events-propagation': {
        global: 'EventWidgets',
        script: 'web/EventWidgets.js',
        label: 'Propagation',
        category: 'Web',
        description: 'Visualisation de la propagation (capture/bubbling) des événements',
        level: 'L1',
        tags: ['propagation', 'bubbling', 'capture', 'events', 'web'],
        defaultConfig: { type: 'events-propagation' },
        staticFallback: _sf('🔔', 'Propagation'),
    },
    'events-delegation': {
        global: 'EventWidgets',
        script: 'web/EventWidgets.js',
        label: "Délégation d'événements",
        category: 'Web',
        description: "Simulation de la délégation d'événements avec cibles dynamiques",
        level: 'L1',
        tags: ['delegation', 'events', 'javascript', 'web'],
        defaultConfig: { type: 'events-delegation' },
        staticFallback: _sf('🎯', "Délégation d'événements"),
    },
    'events-catalog': {
        global: 'EventWidgets',
        script: 'web/EventWidgets.js',
        label: "Catalogue d'événements",
        category: 'Web',
        description: "Catalogue interactif de tous les types d'événements du DOM",
        level: 'L1',
        tags: ['catalog', 'events', 'référence', 'web'],
        defaultConfig: { type: 'events-catalog' },
        staticFallback: _sf('📖', "Catalogue d'événements"),
    },

    // ── Tri ───────────────────────────────────────────────────────────────────
    'sorting-merge': {
        global: 'MergeSortWidget',
        script: 'MergeSortVisualizer.js',
        label: 'Tri fusion (Merge Sort)',
        category: 'Tri',
        description: 'Visualisation bottom-up du tri fusion : chaque étape montre les fusions de sous-tableaux',
        level: 'L2',
        tags: ['tri', 'fusion', 'merge sort', 'diviser pour régner', 'O(n log n)'],
        defaultConfig: { data: [64, 34, 25, 12, 22, 11, 90, 48] },
        staticFallback: _sf('🔀', 'Tri fusion'),
    },
    'sorting-counting': {
        global: 'CountingRadixWidget',
        script: 'CountingRadixVisualizer.js',
        label: 'Tri par comptage',
        category: 'Tri',
        description: 'Visualisation pas-à-pas du counting sort : comptage, cumul et placement',
        level: 'L2',
        tags: ['tri', 'comptage', 'counting sort', 'tableau', 'linéaire', 'O(n+k)'],
        defaultConfig: { data: [4, 2, 7, 1, 3, 5, 0, 6] },
        staticFallback: _sf('🔢', 'Tri par comptage'),
    },
    'sorting-bubble': {
        global: 'SortingWidget',
        script: 'SortingVisualizer.js',
        label: 'Tri à bulles',
        category: 'Tri',
        description: 'Visualisation pas-à-pas du tri à bulles avec comparaisons et échanges colorés',
        level: 'L1',
        tags: ['tri', 'bulle', 'algorithme', 'tableau', 'L1'],
        defaultConfig: { algorithm: 'bubble-sort', data: [64, 34, 25, 12, 22, 11, 90] },
        staticFallback: _sf('🔵', 'Tri à bulles'),
    },
    'sorting-insertion': {
        global: 'SortingWidget',
        script: 'SortingVisualizer.js',
        label: 'Tri par insertion',
        category: 'Tri',
        description: 'Visualisation du tri par insertion : chaque élément est inséré à sa bonne position',
        level: 'L1',
        tags: ['tri', 'insertion', 'algorithme', 'tableau'],
        defaultConfig: { algorithm: 'insertion-sort', data: [64, 34, 25, 12, 22, 11, 90] },
        staticFallback: _sf('🃏', 'Tri par insertion'),
    },
    'sorting-selection': {
        global: 'SortingWidget',
        script: 'SortingVisualizer.js',
        label: 'Tri par sélection',
        category: 'Tri',
        description: 'Visualisation du tri par sélection : recherche du minimum et placement itératif',
        level: 'L1',
        tags: ['tri', 'sélection', 'algorithme', 'tableau', 'minimum'],
        defaultConfig: { algorithm: 'selection-sort', data: [64, 34, 25, 12, 22, 11, 90] },
        staticFallback: _sf('📍', 'Tri par sélection'),
    },
    'sorting-quick': {
        global: 'QuickSortWidget',
        script: 'QuickSortVisualizer.js',
        label: 'Tri rapide (QuickSort)',
        category: 'Tri',
        description: 'Visualisation du tri rapide pas-à-pas : partitionnement Lomuto avec pivot surligné',
        level: 'L2',
        tags: ['tri', 'rapide', 'quicksort', 'pivot', 'récursif', 'O(n log n)'],
        defaultConfig: { data: [64, 34, 25, 12, 22, 11, 90, 48] },
        staticFallback: _sf('⚡', 'Tri rapide'),
    },

    // ── Structures linéaires ──────────────────────────────────────────────────
    'struct-stack': {
        global: 'StructureWidget',
        script: 'StructureVisualizer.js',
        label: 'Pile (Stack)',
        category: 'Structures',
        description: 'Simulation interactive d\'une pile LIFO avec empiler/dépiler et visualisation',
        level: 'L1',
        tags: ['pile', 'stack', 'LIFO', 'structure', 'algorithme'],
        defaultConfig: { type: 'stack' },
        staticFallback: _sf('📚', 'Pile (Stack)'),
    },
    'struct-queue': {
        global: 'StructureWidget',
        script: 'StructureVisualizer.js',
        label: 'File (Queue)',
        category: 'Structures',
        description: 'Simulation interactive d\'une file FIFO avec enfiler/défiler et visualisation',
        level: 'L1',
        tags: ['file', 'queue', 'FIFO', 'structure', 'algorithme'],
        defaultConfig: { type: 'queue' },
        staticFallback: _sf('🚶', 'File (Queue)'),
    },

    // ── Recherche ─────────────────────────────────────────────────────────────
    'search-sequential': {
        global: 'SearchWidget',
        script: 'SearchVisualizer.js',
        label: 'Recherche séquentielle',
        category: 'Recherche',
        description: 'Visualisation de la recherche linéaire élément par élément dans un tableau',
        level: 'L1',
        tags: ['recherche', 'séquentielle', 'linéaire', 'tableau', 'L1'],
        defaultConfig: { algorithm: 'sequential', data: [2, 5, 8, 12, 16, 23, 38, 56, 72, 91], target: 23 },
        staticFallback: _sf('🔍', 'Recherche séquentielle'),
    },
    'search-binary': {
        global: 'SearchWidget',
        script: 'SearchVisualizer.js',
        label: 'Recherche dichotomique',
        category: 'Recherche',
        description: 'Visualisation de la recherche binaire (dichotomique) dans un tableau trié',
        level: 'L1',
        tags: ['recherche', 'binaire', 'dichotomique', 'tableau trié', 'O(log n)'],
        defaultConfig: { algorithm: 'binary', data: [2, 5, 8, 12, 16, 23, 38, 56, 72, 91], target: 23 },
        staticFallback: _sf('⚡', 'Recherche dichotomique'),
    },

    // ── Structures de données ─────────────────────────────────────────────────
    'bst-simulator': {
        global: 'BSTWidget',
        script: 'BinaryTreeVisualizer.js',
        label: 'Arbre binaire de recherche',
        category: 'Structures',
        description: 'Simulation interactive d\'un BST : insertion, suppression, recherche',
        level: 'L2',
        tags: ['arbre', 'bst', 'binaire', 'structure', 'algorithme'],
        defaultConfig: { values: [50, 30, 70, 20, 40, 60, 80] },
        staticFallback: _sf('🌲', 'Arbre binaire de recherche'),
    },
    'struct-linked-list': {
        global: 'LinkedListWidget',
        script: 'LinkedListVisualizer.js',
        label: 'Liste chaînée',
        category: 'Structures',
        description: 'Simulation interactive d\'une liste chaînée : ajout en tête/queue, suppression, recherche',
        level: 'L2',
        tags: ['liste', 'chaînée', 'linked list', 'pointeurs', 'structure', 'L2'],
        defaultConfig: { values: [3, 7, 1, 9, 4] },
        staticFallback: _sf('🔗', 'Liste chaînée'),
    },
    'struct-hash-table': {
        global: 'HashTableWidget',
        script: 'HashTableVisualizer.js',
        label: 'Table de hachage',
        category: 'Structures',
        description: 'Table de hachage avec chaînage : visualisation de h(k)=k mod n, collisions et recherche',
        level: 'L2',
        tags: ['hachage', 'hash table', 'collision', 'chaîne', 'structure'],
        defaultConfig: { buckets: 8, data: [14, 7, 21, 3, 28] },
        staticFallback: _sf('🗂️', 'Table de hachage'),
    },
    'struct-heap-min': {
        global: 'HeapWidget',
        script: 'HeapVisualizer.js',
        label: 'Tas minimum (Min-Heap)',
        category: 'Structures',
        description: 'Tas binaire minimum : insertion avec sift-up, extraction de la racine avec heapify-down',
        level: 'L2',
        tags: ['tas', 'heap', 'minimum', 'arbre', 'priorité', 'structure'],
        defaultConfig: { mode: 'min', data: [15, 10, 20, 8, 12, 30] },
        staticFallback: _sf('⬇️', 'Tas minimum'),
    },
    'struct-heap-max': {
        global: 'HeapWidget',
        script: 'HeapVisualizer.js',
        label: 'Tas maximum (Max-Heap)',
        category: 'Structures',
        description: 'Tas binaire maximum : insertion avec sift-up, extraction de la racine avec heapify-down',
        level: 'L2',
        tags: ['tas', 'heap', 'maximum', 'arbre', 'priorité', 'structure'],
        defaultConfig: { mode: 'max', data: [8, 10, 12, 15, 20, 30] },
        staticFallback: _sf('⬆️', 'Tas maximum'),
    },

    // ── Réseau ────────────────────────────────────────────────────────────────
    'net-tcp': {
        global: 'TcpWidget',
        script: 'reseau/TcpHandshakePage.js',
        label: 'Simulation TCP',
        category: 'Réseau',
        description: '3-way handshake, transfert de données, fermeture et simulation de perte de paquets',
        level: 'L2',
        tags: ['tcp', 'réseau', 'handshake', 'protocole', 'connexion', 'L2'],
        defaultConfig: { scenario: 'normal' },
        staticFallback: _sf('🔌', 'Simulation TCP'),
    },
    'net-ip-subnet': {
        global: 'IpSubnetWidget',
        script: 'reseau/IpSubnetPage.js',
        label: 'Calculateur IP/Masque',
        category: 'Réseau',
        description: 'Calculateur de sous-réseau : adresse réseau, broadcast, plage hôtes, représentation binaire',
        level: 'L2',
        tags: ['ip', 'masque', 'subnet', 'cidr', 'réseau', 'adressage'],
        defaultConfig: { ip: '192.168.1.0/24' },
        staticFallback: _sf('🌐', 'Calculateur IP/Masque'),
    },

    // ── Systèmes ──────────────────────────────────────────────────────────────
    'sys-scheduling': {
        global: 'SchedulingWidget',
        script: 'systemes/SchedulingPage.js',
        label: 'Ordonnancement CPU',
        category: 'Systèmes',
        description: 'Simulation FCFS, SJF, Round Robin et Priorité avec diagramme de Gantt et métriques',
        level: 'L2',
        tags: ['ordonnancement', 'scheduling', 'FCFS', 'SJF', 'round robin', 'Gantt', 'OS'],
        defaultConfig: { algorithm: 'fcfs' },
        staticFallback: _sf('⚙️', 'Ordonnancement CPU'),
    },

    'sys-memory': {
        global: 'MemoryWidget',
        script: 'systemes/MemoryPagingPage.js',
        label: 'Mémoire paginée',
        category: 'Systèmes',
        description: 'Simulation de remplacement de pages : FIFO, LRU et Optimal avec diagramme de cadres',
        level: 'L2',
        tags: ['mémoire', 'pagination', 'FIFO', 'LRU', 'optimal', 'page fault', 'OS'],
        defaultConfig: { sequence: '7,0,1,2,0,3,0,4,2,3,0,3,2', frames: 3 },
        staticFallback: _sf('🗄️', 'Mémoire paginée'),
    },
    'sys-pipeline': {
        global: 'PipelineWidget',
        script: 'systemes/PipelinePage.js',
        label: 'Pipeline processeur',
        category: 'Systèmes',
        description: 'Visualisation du pipeline IF/ID/EX/MEM/WB avec détection des aléas RAW et forwarding',
        level: 'L2',
        tags: ['pipeline', 'processeur', 'aléas', 'forwarding', 'architecture', 'stall', 'RAW'],
        defaultConfig: {},
        staticFallback: _sf('⚡', 'Pipeline processeur'),
    },
    'sys-concurrency': {
        global: 'ConcurrencyWidget',
        script: 'systemes/ConcurrencyPage.js',
        label: 'Concurrence & Deadlock',
        category: 'Systèmes',
        description: 'Simulation mutex (avec/sans verrou) et détection de deadlock par attente circulaire',
        level: 'L2',
        tags: ['concurrence', 'mutex', 'deadlock', 'threads', 'verrou', 'synchronisation', 'OS'],
        defaultConfig: {},
        staticFallback: _sf('🔒', 'Concurrence & Deadlock'),
    },
    'net-dns': {
        global: 'DnsWidget',
        script: 'reseau/DnsSimulatorPage.js',
        label: 'Résolution DNS',
        category: 'Réseau',
        description: 'Simulation de la résolution DNS étape par étape (racine → TLD → autoritaire) avec cache TTL',
        level: 'L1',
        tags: ['DNS', 'réseau', 'résolution', 'domaine', 'TTL', 'cache', 'IP'],
        defaultConfig: {},
        staticFallback: _sf('🌐', 'Résolution DNS'),
    },

    // ── Logique booléenne ─────────────────────────────────────────────────────
    'boolean-gates': {
        global: 'BooleanGatesWidget',
        script: 'concepts/BooleanGatesWidget.js',
        label: 'Portes logiques',
        category: 'Logique',
        description: 'Simulation de portes logiques ET, OU, NON, XOR avec visualisation',
        level: 'L1',
        tags: ['logique', 'portes', 'booléen', 'circuits'],
        defaultConfig: {},
        staticFallback: _sf('⚙️', 'Portes logiques'),
    },
    'boolean-simplifier': {
        global: 'BooleanSimplifierWidget',
        script: 'concepts/BooleanSimplifierWidget.js',
        label: 'Simplificateur booléen',
        category: 'Logique',
        description: 'Simplification d\'expressions booléennes avec table de vérité',
        level: 'L1',
        tags: ['logique', 'algèbre', 'booléen', 'simplification'],
        defaultConfig: {},
        staticFallback: _sf('🔣', 'Simplificateur booléen'),
    },
    'boolean-karnaugh': {
        global: 'BooleanKarnaughWidget',
        script: 'concepts/BooleanKarnaughWidget.js',
        label: 'Tableau de Karnaugh',
        category: 'Logique',
        description: 'Minimisation de fonctions booléennes par tableau de Karnaugh',
        level: 'L2',
        tags: ['karnaugh', 'logique', 'minimisation', 'booléen'],
        defaultConfig: {},
        staticFallback: _sf('🔲', 'Tableau de Karnaugh'),
    },

    // ── Git ───────────────────────────────────────────────────────────────────
    'git-zones': {
        global: 'GitZonesWidget',
        script: 'git/GitZonesWidget.js',
        label: 'Zones Git',
        category: 'Git',
        description: 'Visualisation des zones Git : working dir, staging, repository',
        level: 'L1',
        tags: ['git', 'zones', 'staging', 'commit'],
        defaultConfig: {},
        staticFallback: _sf('📦', 'Zones Git'),
    },
    'git-dag': {
        global: 'GitDAGWidget',
        script: 'git/GitDAGWidget.js',
        label: 'DAG Git',
        category: 'Git',
        description: 'Visualisation du graphe orienté acyclique (DAG) des commits Git',
        level: 'L1',
        tags: ['git', 'dag', 'commits', 'branches', 'graphe'],
        defaultConfig: {},
        staticFallback: _sf('🔀', 'DAG Git'),
    },
    'git-file-lifecycle': {
        global: 'GitFileLifecycleWidget',
        script: 'git/GitFileLifecycleWidget.js',
        label: 'Cycle de vie des fichiers',
        category: 'Git',
        description: 'Cycle de vie d\'un fichier dans Git : untracked → staged → committed',
        level: 'L1',
        tags: ['git', 'fichiers', 'lifecycle', 'status'],
        defaultConfig: {},
        staticFallback: _sf('📄', 'Cycle de vie des fichiers'),
    },
    'git-terminal': {
        global: 'GitTerminalWidget',
        script: 'git/GitTerminalWidget.js',
        label: 'Terminal Git',
        category: 'Git',
        description: 'Terminal Git interactif avec visualisation des effets des commandes',
        level: 'L1',
        tags: ['git', 'terminal', 'commandes', 'cli'],
        defaultConfig: {},
        staticFallback: _sf('💻', 'Terminal Git'),
    },
    'git-strategy-comparator': {
        global: 'GitStrategyComparator',
        script: 'git/GitStrategyComparator.js',
        label: 'Comparateur de stratégies',
        category: 'Git',
        description: 'Comparaison des stratégies de merge, rebase et squash',
        level: 'L2',
        tags: ['git', 'merge', 'rebase', 'squash', 'stratégie'],
        defaultConfig: {},
        staticFallback: _sf('⚖️', 'Comparateur de stratégies'),
    },
    'git-conflict-editor': {
        global: 'GitConflictEditorWidget',
        script: 'git/GitConflictEditorWidget.js',
        label: 'Éditeur de conflits',
        category: 'Git',
        description: 'Simulation et résolution interactive de conflits de merge Git',
        level: 'L2',
        tags: ['git', 'conflits', 'merge', 'résolution'],
        defaultConfig: {},
        staticFallback: _sf('⚔️', 'Éditeur de conflits'),
    },
    'git-flow-simulator': {
        global: 'GitflowSimulatorWidget',
        script: 'git/GitflowSimulatorWidget.js',
        label: 'Gitflow Simulator',
        category: 'Git',
        description: 'Simulation du workflow Gitflow avec branches feature/release/hotfix',
        level: 'L2',
        tags: ['git', 'gitflow', 'branches', 'workflow'],
        defaultConfig: {},
        staticFallback: _sf('🌊', 'Gitflow Simulator'),
    },
    'git-cicd-pipeline': {
        global: 'CICDPipelineWidget',
        script: 'git/CICDPipelineWidget.js',
        label: 'Pipeline CI/CD',
        category: 'GitHub Actions',
        description: 'Visualisation d\'un pipeline CI/CD avec étapes build/test/deploy',
        level: 'L2',
        tags: ['ci', 'cd', 'pipeline', 'github', 'devops'],
        defaultConfig: {},
        staticFallback: _sf('🔄', 'Pipeline CI/CD'),
    },
    'git-rebase-interactive': {
        global: 'GitRebaseInteractiveWidget',
        script: 'git/GitRebaseInteractiveWidget.js',
        label: 'Rebase interactif',
        category: 'Git',
        description: 'Simulation du rebase interactif Git avec pick/squash/fixup',
        level: 'L2',
        tags: ['git', 'rebase', 'interactive', 'historique'],
        defaultConfig: {},
        staticFallback: _sf('✂️', 'Rebase interactif'),
    },
    'git-bisect': {
        global: 'GitBisectWidget',
        script: 'git/GitBisectWidget.js',
        label: 'Git Bisect',
        category: 'Git',
        description: 'Recherche dichotomique d\'un commit bogué avec git bisect',
        level: 'L2',
        tags: ['git', 'bisect', 'debug', 'recherche'],
        defaultConfig: {},
        staticFallback: _sf('🔍', 'Git Bisect'),
    },
    'git-reset-visualizer': {
        global: 'GitResetVisualizerWidget',
        script: 'git/GitResetVisualizerWidget.js',
        label: 'Git Reset',
        category: 'Git',
        description: 'Visualisation des modes git reset : --soft, --mixed, --hard',
        level: 'L2',
        tags: ['git', 'reset', 'revert', 'historique'],
        defaultConfig: {},
        staticFallback: _sf('↩️', 'Git Reset'),
    },
    'git-merge-comparison': {
        global: 'GitMergeComparisonWidget',
        script: 'git/GitMergeComparisonWidget.js',
        label: 'Comparaison de merge',
        category: 'Git',
        description: 'Comparaison visuelle merge vs rebase vs fast-forward',
        level: 'L2',
        tags: ['git', 'merge', 'rebase', 'fast-forward'],
        defaultConfig: {},
        staticFallback: _sf('🔀', 'Comparaison de merge'),
    },
    'github-actions-widget': {
        global: 'GitHubActionsWidget',
        script: 'git/GitHubActionsWidget.js',
        label: 'Anatomie YAML Actions',
        category: 'GitHub Actions',
        description: 'Exploration de la structure d\'un fichier YAML GitHub Actions',
        level: 'L2',
        tags: ['github', 'actions', 'yaml', 'ci', 'workflow'],
        defaultConfig: {},
        staticFallback: _sf('📝', 'Anatomie YAML Actions'),
    },
    'git-commit-signing': {
        global: 'GitCommitSigningWidget',
        script: 'git/GitCommitSigningWidget.js',
        label: 'Signature de commits',
        category: 'Git',
        description: 'Démonstration de la signature GPG/SSH des commits Git',
        level: 'L3',
        tags: ['git', 'gpg', 'signature', 'sécurité'],
        defaultConfig: {},
        staticFallback: _sf('🔏', 'Signature de commits'),
    },
    'git-secret-scanning': {
        global: 'GitSecretScanningWidget',
        script: 'git/GitSecretScanningWidget.js',
        label: 'Secret scanning',
        category: 'Git',
        description: 'Détection de secrets (tokens, clés) dans les dépôts Git',
        level: 'L2',
        tags: ['git', 'sécurité', 'secrets', 'scanning'],
        defaultConfig: {},
        staticFallback: _sf('🔐', 'Secret scanning'),
    },
    'codeowners-simulator': {
        global: 'CODEOWNERSSimulatorWidget',
        script: 'git/CODEOWNERSSimulatorWidget.js',
        label: 'CODEOWNERS Simulator',
        category: 'GitHub',
        description: 'Simulation du fichier CODEOWNERS et des règles de review',
        level: 'L2',
        tags: ['github', 'codeowners', 'review', 'permissions'],
        defaultConfig: {},
        staticFallback: _sf('👥', 'CODEOWNERS Simulator'),
    },
    'secret-leak-timeline': {
        global: 'SecretLeakTimelineWidget',
        script: 'git/SecretLeakTimelineWidget.js',
        label: 'Secret Leak Timeline',
        category: 'GitHub',
        description: 'Timeline de fuite de secret depuis un commit jusqu\'à la détection',
        level: 'L2',
        tags: ['sécurité', 'secrets', 'leak', 'timeline'],
        defaultConfig: {},
        staticFallback: _sf('⏱️', 'Secret Leak Timeline'),
    },
    'dependabot-alert': {
        global: 'DependabotAlertWidget',
        script: 'git/DependabotAlertWidget.js',
        label: 'Dependabot Alert',
        category: 'GitHub',
        description: 'Simulation des alertes Dependabot pour les dépendances vulnérables',
        level: 'L2',
        tags: ['github', 'dependabot', 'sécurité', 'dépendances'],
        defaultConfig: {},
        staticFallback: _sf('🤖', 'Dependabot Alert'),
    },
    'git-filter-repo': {
        global: 'GitFilterRepoWidget',
        script: 'git/GitFilterRepoWidget.js',
        label: 'Filter-repo',
        category: 'Git',
        description: 'Démonstration de git-filter-repo pour réécrire l\'historique',
        level: 'L3',
        tags: ['git', 'filter-repo', 'historique', 'réécriture'],
        defaultConfig: {},
        staticFallback: _sf('🧹', 'Filter-repo'),
    },
    'workflow-trigger-simulator': {
        global: 'WorkflowTriggerSimulatorWidget',
        script: 'git/WorkflowTriggerSimulatorWidget.js',
        label: 'Déclencheurs workflow',
        category: 'GitHub Actions',
        description: 'Simulation des déclencheurs (triggers) GitHub Actions',
        level: 'L2',
        tags: ['github', 'actions', 'triggers', 'workflow'],
        defaultConfig: {},
        staticFallback: _sf('▶️', 'Déclencheurs workflow'),
    },
    'job-dependency-graph': {
        global: 'JobDependencyGraphWidget',
        script: 'git/JobDependencyGraphWidget.js',
        label: 'Pipeline de jobs',
        category: 'GitHub Actions',
        description: 'Graphe de dépendances des jobs dans un workflow GitHub Actions',
        level: 'L2',
        tags: ['github', 'actions', 'jobs', 'pipeline', 'dépendances'],
        defaultConfig: {},
        staticFallback: _sf('🕸️', 'Pipeline de jobs'),
    },
    'matrix-builder': {
        global: 'MatrixBuilderWidget',
        script: 'git/MatrixBuilderWidget.js',
        label: 'Matrix build',
        category: 'GitHub Actions',
        description: 'Construction de matrices de build pour les workflows GitHub Actions',
        level: 'L2',
        tags: ['github', 'actions', 'matrix', 'build'],
        defaultConfig: {},
        staticFallback: _sf('🔢', 'Matrix build'),
    },

    // ── GitHub ────────────────────────────────────────────────────────────────
    'github-pr-lifecycle': {
        global: 'GitHubPRLifecycleWidget',
        script: 'git/GitHubPRLifecycleWidget.js',
        label: "Cycle de vie d'une PR",
        category: 'GitHub',
        description: "Cycle de vie d'une Pull Request de l'ouverture à la fusion",
        level: 'L1',
        tags: ['github', 'pr', 'pull request', 'review', 'merge'],
        defaultConfig: {},
        staticFallback: _sf('🔀', "Cycle de vie d'une PR"),
    },
    'github-issue-tracker': {
        global: 'GitHubIssueTrackerWidget',
        script: 'git/GitHubIssueTrackerWidget.js',
        label: 'Issue Tracker',
        category: 'GitHub',
        description: 'Simulation du suivi d\'issues GitHub avec labels et milestones',
        level: 'L1',
        tags: ['github', 'issues', 'tracker', 'labels'],
        defaultConfig: {},
        staticFallback: _sf('🐛', 'Issue Tracker'),
    },
    'github-kanban': {
        global: 'GitHubKanbanWidget',
        script: 'git/GitHubKanbanWidget.js',
        label: 'Kanban Board',
        category: 'GitHub',
        description: 'Tableau Kanban GitHub Projects avec colonnes et cartes',
        level: 'L1',
        tags: ['github', 'kanban', 'projects', 'agile'],
        defaultConfig: {},
        staticFallback: _sf('📋', 'Kanban Board'),
    },
    'github-roadmap': {
        global: 'GitHubRoadmapWidget',
        script: 'git/GitHubRoadmapWidget.js',
        label: 'GitHub Roadmap',
        category: 'GitHub',
        description: 'Roadmap visuelle GitHub Projects avec vue timeline',
        level: 'L1',
        tags: ['github', 'roadmap', 'planning', 'timeline'],
        defaultConfig: {},
        staticFallback: _sf('🗺️', 'GitHub Roadmap'),
    },
    'git-branch-protection': {
        global: 'BranchProtectionWidget',
        script: 'git/BranchProtectionWidget.js',
        label: 'Règles de protection',
        category: 'GitHub',
        description: 'Configuration des règles de protection de branches sur GitHub',
        level: 'L2',
        tags: ['github', 'branches', 'protection', 'règles', 'sécurité'],
        defaultConfig: {},
        staticFallback: _sf('🛡️', 'Règles de protection'),
    },
};

// Expose globally
if (typeof window !== 'undefined') window.OEI_WIDGET_REGISTRY = OEI_WIDGET_REGISTRY;
