/**
 * @throws {Error} Peut lever une erreur de chargement si le module est execute hors contexte navigateur.
 * @module slides/slides-editor
 * @public
 * @internal Module Slides charge cote navigateur.
 * @typedef {Object} OeiDocMarker
 * @property {string} scope - Portee documentaire du module.
 * @deprecated Type provisoire documentant un module legacy en migration.
 * @example
 * // Chargement navigateur:
 * // <script src="../shared/slides/slides-editor.js"></script>
 */
/**
 * slides-editor.js — SlidesEditor
 * Gère l'état de la présentation en cours d'édition.
 * Indépendant du DOM de l'éditeur : l'UI est dans editor.html.
 */

/**
 * Repair JSON text generated by AI (Gemini, ChatGPT…) that may contain:
 * - Literal newlines inside string values (stripped)
 * - Unescaped double-quotes inside string values (escaped to \")
 * Uses structure-aware parsing to distinguish real string boundaries
 * from unescaped quotes (tracks object vs array context).
 */
function _repairJsonText(raw) {
    const n = raw.length;
    const out = [];
    let i = 0;

    function skipWs() { while (i < n && ' \t\n\r'.includes(raw[i])) i++; }

    function readString(ctx) {
        // ctx: 'key' | 'obj-val' | 'arr-val'
        // We are at the opening "
        out.push('"'); i++;
        while (i < n) {
            const ch = raw[i];
            if (ch === '\\') { out.push(ch); i++; if (i < n) { out.push(raw[i]); i++; } continue; }
            if (ch === '\n' || ch === '\r') { i++; continue; } // strip literal newlines
            if (ch === '"') {
                // Look ahead past whitespace to decide if this closes the string
                let j = i + 1;
                while (j < n && ' \t\n\r'.includes(raw[j])) j++;
                const nxt = j < n ? raw[j] : '';
                let isClose = false;
                if (ctx === 'key') {
                    isClose = (nxt === ':');
                } else if (ctx === 'obj-val') {
                    if (nxt === '}' || nxt === ']' || nxt === '') { isClose = true; }
                    else if (nxt === ',') {
                        // In object, after comma we expect "key": — validate lookahead
                        let k = j + 1;
                        while (k < n && ' \t\n\r'.includes(raw[k])) k++;
                        if (k < n && raw[k] === '"') {
                            // Find end of potential key
                            k++;
                            while (k < n) { if (raw[k] === '\\') { k += 2; continue; } if (raw[k] === '"') break; k++; }
                            if (k < n) {
                                k++; // past "
                                while (k < n && ' \t\n\r'.includes(raw[k])) k++;
                                isClose = (k < n && raw[k] === ':');
                            }
                        } else if (k < n && raw[k] === '}') {
                            // trailing comma before }
                            isClose = true;
                        }
                    }
                } else { // arr-val
                    isClose = (nxt === ']' || nxt === ',' || nxt === '}' || nxt === '');
                }
                if (isClose) { out.push('"'); i++; return; }
                // Not a real close — escape it
                out.push('\\"'); i++; continue;
            }
            out.push(ch); i++;
        }
    }

    function readValue(ctx) {
        skipWs(); if (i >= n) return;
        const ch = raw[i];
        if (ch === '"') readString(ctx);
        else if (ch === '{') readObject();
        else if (ch === '[') readArray();
        else if ('tfn'.includes(ch)) { while (i < n && raw[i] >= 'a' && raw[i] <= 'z') { out.push(raw[i]); i++; } }
        else if (ch === '-' || (ch >= '0' && ch <= '9')) { while (i < n && '-+0123456789.eE'.includes(raw[i])) { out.push(raw[i]); i++; } }
    }

    function readObject() {
        out.push('{'); i++; skipWs();
        if (i < n && raw[i] === '}') { out.push('}'); i++; return; }
        while (i < n) {
            skipWs();
            if (i < n && raw[i] === '"') readString('key');
            skipWs();
            if (i < n && raw[i] === ':') { out.push(':'); i++; }
            skipWs();
            readValue('obj-val');
            skipWs();
            if (i < n && raw[i] === ',') { out.push(','); i++; }
            else if (i < n && raw[i] === '}') { out.push('}'); i++; return; }
            else break;
        }
    }

    function readArray() {
        out.push('['); i++; skipWs();
        if (i < n && raw[i] === ']') { out.push(']'); i++; return; }
        while (i < n) {
            skipWs();
            readValue('arr-val');
            skipWs();
            if (i < n && raw[i] === ',') { out.push(','); i++; }
            else if (i < n && raw[i] === ']') { out.push(']'); i++; return; }
            else break;
        }
    }

    skipWs();
    if (i < n && raw[i] === '{') readObject();
    else if (i < n && raw[i] === '[') readArray();
    else return raw; // not JSON object/array, return as-is

    return out.join('');
}
window._repairJsonText = _repairJsonText;

class SlidesEditor {
    static STORAGE_KEY = window.OEIStorage?.KEYS?.SLIDE_DRAFT || 'oei-slide-draft';
    static WORKDOCS_KEY = window.OEIStorage?.KEYS?.SLIDE_WORKDOCS || 'oei-slide-workdocs';
    static MAX_WORKDOCS = 10;
    static WORKDOC_TIMELINE_LIMIT = 40;
    static WORKDOC_TIMELINE_MIN_INTERVAL_MS = 20_000;
    static CURRENT_SCHEMA_VERSION = 2;

    static SLIDE_TYPES = [
        { id: 'canvas',     icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 8h3v3H8zM14 8h3v2h-3M7 15h5v2H7"/></svg>',  label: 'Canvas libre' },
        { id: 'title',      icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7 10h10" stroke-width="2.5"/><path d="M9 14h6" opacity="0.4"/></svg>',  label: 'Titre' },
        { id: 'chapter',    icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7 9h10" stroke-width="2"/><path d="M7 13h6" opacity="0.4"/><path d="M7 16h10" opacity="0.25"/></svg>',  label: 'Chapitre' },
        { id: 'bullets',    icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 9h8M8 12h7M8 15h5"/><circle cx="6.5" cy="9" r=".7" fill="currentColor" stroke="none"/><circle cx="6.5" cy="12" r=".7" fill="currentColor" stroke="none"/><circle cx="6.5" cy="15" r=".7" fill="currentColor" stroke="none"/></svg>',  label: 'Points clés' },
        { id: 'code',       icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><polyline points="8 9 6 12 8 15"/><polyline points="16 9 18 12 16 15"/><line x1="13" y1="8" x2="11" y2="16" opacity="0.4"/></svg>',  label: 'Code' },
        { id: 'split',      icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="12" y1="5" x2="12" y2="19" opacity="0.3"/><path d="M6 9h4M6 12h3" opacity="0.5"/><path d="M14 9h4M14 12h3" opacity="0.5"/></svg>', label: 'Split' },
        { id: 'definition', icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7 9h4" stroke-width="2.5"/><path d="M7 13h10" opacity="0.4"/><path d="M7 16h8" opacity="0.3"/></svg>',  label: 'Définition' },
        { id: 'comparison', icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="12" y1="5" x2="12" y2="19" opacity="0.3"/><path d="M6 9h4M6 12h3" opacity="0.5"/><path d="M14 9h4M14 12h3" opacity="0.5"/></svg>',  label: 'Comparaison' },
        { id: 'simulation', icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><polygon points="10 8 16 12 10 16" fill="currentColor" opacity="0.3" stroke="none"/><polygon points="10 8 16 12 10 16"/></svg>',  label: 'Simulation' },
        { id: 'image',      icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/></svg>',  label: 'Image' },
        { id: 'quote',      icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M10 10V8a2 2 0 00-2-2H7v4h3zM17 10V8a2 2 0 00-2-2h-1v4h3z" fill="currentColor" opacity="0.3"/><path d="M8 14h8" opacity="0.4"/></svg>',  label: 'Citation' },
        { id: 'quiz',       icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="7" cy="9" r="1.5" fill="currentColor" opacity="0.3"/><path d="M10 9h8" opacity="0.5"/><circle cx="7" cy="14" r="1.5" opacity="0.3"/><path d="M10 14h6" opacity="0.5"/><circle cx="7" cy="19" r="1.5" opacity="0.3"/><path d="M10 19h5" opacity="0.3"/></svg>',  label: 'Quiz' },
        { id: 'blank',      icon: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2" stroke-dasharray="3 2"/></svg>',  label: 'Libre' },
    ];

    // WIDGET_OPTIONS est dérivé dynamiquement depuis OEI_WIDGET_REGISTRY (WidgetRegistry.js).
    // Chaque nouveau widget ajouté au registre apparaît automatiquement dans l'éditeur.
    static get WIDGET_OPTIONS() {
        const reg = window.OEI_WIDGET_REGISTRY || {};
        return Object.entries(reg)
            .filter(([, r]) => r.label && r.category)
            .map(([id, r]) => ({ id, label: r.label, category: r.category, description: r.description || '', level: r.level || '' }));
    }

    static DEFAULT_SLIDE(type = 'bullets') {
        const defaults = {
            title:      { type: 'title',      title: 'Nouveau titre', subtitle: '', author: '' },
            chapter:    { type: 'chapter',    title: 'Nouveau chapitre', number: '', subtitle: '' },
            bullets:    { type: 'bullets',    title: 'Points clés', items: ['Premier point', 'Deuxième point', 'Troisième point'] },
            code:       { type: 'code',       title: 'Exemple de code', language: 'python', code: '# Votre code ici\nprint("Hello, World!")' },
            split:      { type: 'split',      title: 'Comparaison', left: { label: 'Avant', type: 'bullets', items: ['Point A', 'Point B'] }, right: { label: 'Après', type: 'bullets', items: ['Point X', 'Point Y'] } },
            definition: { type: 'definition', title: 'Définition', term: 'Terme', definition: 'La définition du terme.' },
            comparison: { type: 'comparison', title: 'Comparaison', left: { title: 'Option A', items: ['Avantage 1', 'Avantage 2'] }, right: { title: 'Option B', items: ['Avantage X', 'Avantage Y'] } },
            simulation: { type: 'simulation', title: 'Simulation', widget: 'workflow-trigger-simulator', config: {} },
            image:      { type: 'image',      title: 'Illustration', src: '', caption: '' },
            quote:      { type: 'quote',      quote: 'La citation ici.', author: 'Auteur' },
            blank:      { type: 'blank',      html: '<p style="color:var(--sl-text)">Contenu libre</p>' },
            quiz:       { type: 'quiz',       title: 'Question ?', quizType: 'mcq', options: ['Réponse A', 'Réponse B', 'Réponse C', 'Réponse D'], answer: '0', explanation: '' },
            canvas:     { type: 'canvas',     elements: [], connectors: [] },
        };
        return { ...(defaults[type] || defaults.bullets) };
    }

    static DEFAULT_PRESENTATION() {
        return {
            schemaVersion: SlidesEditor.CURRENT_SCHEMA_VERSION,
            metadata: {
                title: 'Nouvelle présentation',
                author: '',
                created: new Date().toISOString().slice(0, 10),
                modified: new Date().toISOString().slice(0, 10),
            },
            theme: 'dark',
            showSlideNumber: false,
            footerText: null,
            autoNumberChapters: false,
            reviewComments: [],
            typography: {
                heading: 52,
                text: 22,
            },
            slides: [
                SlidesEditor.DEFAULT_SLIDE('title'),
                SlidesEditor.DEFAULT_SLIDE('bullets'),
            ],
        };
    }

    constructor(onUpdate) {
        this.data = null;
        this.selectedIndex = 0;
        this.selectedSlides = new Set([0]);
        this._slideSelectionAnchor = 0;
        this.onUpdate = onUpdate || (() => {});
        this._historyStack = [];
        this._historyIndex = -1;
        this._pushDebounceTimer = null;
        this._lastRevisionSnapshotAt = 0;
    }

    // ── Lifecycle ──────────────────────────────────────────

    new() {
        this.data = SlidesEditor.DEFAULT_PRESENTATION();
        this._ensurePresentationDefaults();
        this._ensureTypographyDefaults();
        this.selectedIndex = 0;
        this.selectedSlides = new Set([0]);
        this._slideSelectionAnchor = 0;
        this._historyStack = [];
        this._historyIndex = -1;
        this._push();
        this.onUpdate('new');
    }

    load(data) {
        let incoming = data;
        if (window.OEIImportPipeline?.normalizeData) {
            try {
                incoming = window.OEIImportPipeline.normalizeData(data).data;
            } catch (_) {
                incoming = data;
            }
        }
        this.data = JSON.parse(JSON.stringify(incoming)); // deep clone
        this._ensurePresentationDefaults();
        this._ensureTypographyDefaults();
        this._normalizeLegacyCanvasFontSizes();
        this.selectedIndex = 0;
        this.selectedSlides = new Set([0]);
        this._slideSelectionAnchor = 0;
        this._historyStack = [];
        this._historyIndex = -1;
        this._push();
        this.onUpdate('load');
    }

    // ── Metadata ───────────────────────────────────────────

    setMetadata(key, value) {
        this.data.metadata[key] = value;
        this.data.metadata.modified = new Date().toISOString().slice(0, 10);
        this._push();
        this.onUpdate('meta');
    }

    setTheme(themeIdOrObject) {
        this.data.theme = themeIdOrObject;
        this._push();
        this.onUpdate('theme');
    }

    setTypographyDefaults(patch = {}) {
        this._ensureTypographyDefaults();
        this._normalizeLegacyCanvasFontSizes();
        const next = { ...this.data.typography };
        if (Object.prototype.hasOwnProperty.call(patch, 'heading')) {
            const n = Number(patch.heading);
            if (Number.isFinite(n)) next.heading = Math.max(12, Math.min(160, Math.round(n)));
        }
        if (Object.prototype.hasOwnProperty.call(patch, 'text')) {
            const n = Number(patch.text);
            if (Number.isFinite(n)) next.text = Math.max(10, Math.min(120, Math.round(n)));
        }
        this.data.typography = next;
        this._push();
        this.onUpdate('typography');
    }

    _ensureTypographyDefaults() {
        if (!this.data || typeof this.data !== 'object') return;
        const raw = (this.data.typography && typeof this.data.typography === 'object')
            ? this.data.typography
            : {};
        const heading = Number(raw.heading);
        const text = Number(raw.text);
        this.data.typography = {
            heading: Number.isFinite(heading) ? Math.max(12, Math.min(160, Math.round(heading))) : 52,
            text: Number.isFinite(text) ? Math.max(10, Math.min(120, Math.round(text))) : 22,
        };
    }

    _ensurePresentationDefaults() {
        if (!this.data || typeof this.data !== 'object') return;
        if (!this.data.metadata || typeof this.data.metadata !== 'object') this.data.metadata = {};
        const schema = Number(this.data.schemaVersion);
        this.data.schemaVersion = Number.isFinite(schema)
            ? Math.max(0, Math.trunc(schema))
            : SlidesEditor.CURRENT_SCHEMA_VERSION;
        if (typeof this.data.showSlideNumber !== 'boolean') this.data.showSlideNumber = false;
        if (!Object.prototype.hasOwnProperty.call(this.data, 'footerText')) this.data.footerText = null;
        if (typeof this.data.autoNumberChapters !== 'boolean') this.data.autoNumberChapters = false;
        if (!Array.isArray(this.data.reviewComments)) this.data.reviewComments = [];
    }

    _normalizeLegacyCanvasFontSizes() {
        const legacyDefaults = {
            heading: 52,
            text: 22,
            list: 22,
            code: 16,
            highlight: 16,
            definition: 16,
            'callout-box': 18,
            'exercise-block': 18,
            'mistake-fix': 17,
            'code-example': 16,
            'terminal-session': 16,
            shape: 16,
            diagramme: 16,
            quote: 26,
            card: 18,
            table: 18,
            latex: 32,
            timer: 48,
        };
        const slides = Array.isArray(this.data?.slides) ? this.data.slides : [];
        for (const slide of slides) {
            if (!slide || slide.type !== 'canvas' || !Array.isArray(slide.elements)) continue;
            for (const el of slide.elements) {
                if (!el || typeof el !== 'object' || !el.style || typeof el.style !== 'object') continue;
                const legacy = legacyDefaults[el.type];
                if (!Number.isFinite(legacy)) continue;
                const raw = el.style.fontSize;
                const fs = typeof raw === 'string' ? parseFloat(raw) : Number(raw);
                if (!Number.isFinite(fs)) continue;
                if (Math.round(fs) === legacy) {
                    delete el.style.fontSize;
                }
            }
        }
    }

    _clampSlideIndex(index) {
        const n = this.data?.slides?.length || 0;
        if (n <= 0) return 0;
        const i = Number(index);
        if (!Number.isFinite(i)) return 0;
        return Math.max(0, Math.min(n - 1, Math.trunc(i)));
    }

    _sanitizeSlideIndices(indices) {
        const n = this.data?.slides?.length || 0;
        if (n <= 0) return [];
        const src = Array.isArray(indices) ? indices : [];
        const uniq = new Set();
        src.forEach((value) => {
            const i = Number(value);
            if (!Number.isFinite(i)) return;
            const clamped = Math.trunc(i);
            if (clamped < 0 || clamped >= n) return;
            uniq.add(clamped);
        });
        const out = Array.from(uniq);
        out.sort((a, b) => a - b);
        return out;
    }

    _syncSelectionAfterDataChange() {
        const n = this.data?.slides?.length || 0;
        if (n <= 0) {
            this.selectedIndex = 0;
            this.selectedSlides = new Set([0]);
            this._slideSelectionAnchor = 0;
            return;
        }
        this.selectedIndex = this._clampSlideIndex(this.selectedIndex);
        const normalized = this._sanitizeSlideIndices(Array.from(this.selectedSlides || []));
        const finalIndices = normalized.length ? normalized : [this.selectedIndex];
        if (!finalIndices.includes(this.selectedIndex)) this.selectedIndex = finalIndices[finalIndices.length - 1];
        this.selectedSlides = new Set(finalIndices);
        this._slideSelectionAnchor = this._clampSlideIndex(this._slideSelectionAnchor);
    }

    // ── Slide CRUD ─────────────────────────────────────────

    addSlide(type = 'bullets', afterIndex = null) {
        const idx = afterIndex !== null ? afterIndex + 1 : this.data.slides.length;
        const slide = SlidesEditor.DEFAULT_SLIDE(type);
        this.data.slides.splice(idx, 0, slide);
        this.selectedIndex = idx;
        this.selectedSlides = new Set([idx]);
        this._slideSelectionAnchor = idx;
        this._push();
        this.onUpdate('slides');
    }

    insertSlides(slides, afterIndex = null) {
        const src = Array.isArray(slides) ? slides : [];
        if (!src.length) return;
        const insertAt = afterIndex == null
            ? this.data.slides.length
            : this._clampSlideIndex(afterIndex) + 1;
        const clones = src.map((slide) => JSON.parse(JSON.stringify(slide)));
        this.data.slides.splice(insertAt, 0, ...clones);
        const indices = clones.map((_, i) => insertAt + i);
        this.selectedIndex = indices[indices.length - 1];
        this.selectedSlides = new Set(indices);
        this._slideSelectionAnchor = indices[0];
        this._push();
        this.onUpdate('slides');
    }

    duplicateSlide(index) {
        const copy = JSON.parse(JSON.stringify(this.data.slides[index]));
        this.data.slides.splice(index + 1, 0, copy);
        this.selectedIndex = index + 1;
        this.selectedSlides = new Set([this.selectedIndex]);
        this._slideSelectionAnchor = this.selectedIndex;
        this._push();
        this.onUpdate('slides');
    }

    duplicateSlides(indices) {
        const sorted = this._sanitizeSlideIndices(indices);
        if (!sorted.length) return;
        let offset = 0;
        const inserted = [];
        sorted.forEach((idx) => {
            const source = this.data.slides[idx + offset];
            const copy = JSON.parse(JSON.stringify(source));
            const insertAt = idx + offset + 1;
            this.data.slides.splice(insertAt, 0, copy);
            inserted.push(insertAt);
            offset += 1;
        });
        this.selectedIndex = inserted[inserted.length - 1];
        this.selectedSlides = new Set(inserted);
        this._slideSelectionAnchor = inserted[0];
        this._push();
        this.onUpdate('slides');
    }

    removeSlide(index) {
        if (this.data.slides.length <= 1) return;
        this.data.slides.splice(index, 1);
        this.selectedIndex = Math.min(this.selectedIndex, this.data.slides.length - 1);
        this.selectedSlides = new Set([this.selectedIndex]);
        this._slideSelectionAnchor = this.selectedIndex;
        this._push();
        this.onUpdate('slides');
    }

    removeSlides(indices) {
        const sorted = this._sanitizeSlideIndices(indices);
        if (!sorted.length) return;
        if (this.data.slides.length - sorted.length < 1) return;
        const first = sorted[0];
        [...sorted].reverse().forEach((idx) => {
            this.data.slides.splice(idx, 1);
        });
        const next = this._clampSlideIndex(first);
        this.selectedIndex = next;
        this.selectedSlides = new Set([next]);
        this._slideSelectionAnchor = next;
        this._push();
        this.onUpdate('slides');
    }

    moveSlide(from, to) {
        if (to < 0 || to >= this.data.slides.length) return;
        const [slide] = this.data.slides.splice(from, 1);
        this.data.slides.splice(to, 0, slide);
        this.selectedIndex = to;
        this.selectedSlides = new Set([to]);
        this._slideSelectionAnchor = to;
        this._push();
        this.onUpdate('slides');
    }

    moveSlides(indices, targetIndex) {
        const sorted = this._sanitizeSlideIndices(indices);
        if (!sorted.length) return;
        const total = this.data.slides.length;
        let insertion = Number(targetIndex);
        if (!Number.isFinite(insertion)) return;
        insertion = Math.max(0, Math.min(total, Math.trunc(insertion)));
        if (insertion >= sorted[0] && insertion <= sorted[sorted.length - 1] + 1) return;

        const selectedSet = new Set(sorted);
        const moving = sorted.map((idx) => this.data.slides[idx]);
        const remaining = this.data.slides.filter((_, idx) => !selectedSet.has(idx));
        const removedBefore = sorted.filter((idx) => idx < insertion).length;
        const insertInRemaining = Math.max(0, Math.min(remaining.length, insertion - removedBefore));
        this.data.slides = [
            ...remaining.slice(0, insertInRemaining),
            ...moving,
            ...remaining.slice(insertInRemaining),
        ];
        const newIndices = moving.map((_, i) => insertInRemaining + i);
        this.selectedIndex = newIndices[newIndices.length - 1];
        this.selectedSlides = new Set(newIndices);
        this._slideSelectionAnchor = newIndices[0];
        this._push();
        this.onUpdate('slides');
    }

    updateSlide(index, patch) {
        Object.assign(this.data.slides[index], patch);
        this._pushDebounced();
        this.onUpdate('slide-update');
    }

    replaceSlide(index, slide) {
        this.data.slides[index] = slide;
        this._pushDebounced();
        this.onUpdate('slide-update');
    }

    selectSlide(index, options = {}) {
        const idx = this._clampSlideIndex(index);
        const mode = options && typeof options === 'object' ? options : {};
        if (mode.range) {
            this.extendSlideSelection(idx);
            return;
        }
        if (mode.additive) {
            this.toggleSlideSelection(idx);
            return;
        }
        this.selectedIndex = idx;
        this.selectedSlides = new Set([idx]);
        this._slideSelectionAnchor = idx;
        this.onUpdate('select');
    }

    setSlideSelection(indices, options = {}) {
        const sorted = this._sanitizeSlideIndices(indices);
        if (!sorted.length) return;
        const last = sorted[sorted.length - 1];
        this.selectedIndex = this._clampSlideIndex(
            options?.focusIndex != null ? options.focusIndex : last,
        );
        this.selectedSlides = new Set(sorted);
        this._slideSelectionAnchor = this._clampSlideIndex(
            options?.anchorIndex != null ? options.anchorIndex : this._slideSelectionAnchor,
        );
        this.onUpdate('select');
    }

    clearSlideSelection() {
        const idx = this._clampSlideIndex(this.selectedIndex);
        this.selectedSlides = new Set([idx]);
        this._slideSelectionAnchor = idx;
        this.onUpdate('select');
    }

    toggleSlideSelection(index) {
        const idx = this._clampSlideIndex(index);
        const next = new Set(this.selectedSlides || []);
        if (next.has(idx)) {
            if (next.size === 1) return;
            next.delete(idx);
            const sorted = this._sanitizeSlideIndices(Array.from(next));
            this.selectedSlides = new Set(sorted);
            this.selectedIndex = sorted[sorted.length - 1];
        } else {
            next.add(idx);
            const sorted = this._sanitizeSlideIndices(Array.from(next));
            this.selectedSlides = new Set(sorted);
            this.selectedIndex = idx;
        }
        this._slideSelectionAnchor = idx;
        this.onUpdate('select');
    }

    extendSlideSelection(index) {
        const idx = this._clampSlideIndex(index);
        const anchor = this._clampSlideIndex(this._slideSelectionAnchor);
        const start = Math.min(anchor, idx);
        const end = Math.max(anchor, idx);
        const range = [];
        for (let i = start; i <= end; i += 1) range.push(i);
        this.selectedSlides = new Set(range);
        this.selectedIndex = idx;
        this.onUpdate('select');
    }

    getSelectedSlideIndices() {
        this._syncSelectionAfterDataChange();
        return this._sanitizeSlideIndices(Array.from(this.selectedSlides));
    }

    isSlideSelected(index) {
        const idx = this._clampSlideIndex(index);
        return this.selectedSlides?.has(idx) || false;
    }

    get currentSlide() {
        return this.data?.slides?.[this.selectedIndex] || null;
    }

    // ── History ────────────────────────────────────────────

    static MAX_HISTORY = 100;
    static PUSH_DEBOUNCE_MS = 300;

    _push() {
        // Cancel any pending debounced push — we're pushing immediately
        clearTimeout(this._pushDebounceTimer);
        this._pushDebounceTimer = null;

        const snap = JSON.stringify(this.data);
        // Truncate forward history
        this._historyStack = this._historyStack.slice(0, this._historyIndex + 1);
        this._historyStack.push(snap);
        // Limit history size
        if (this._historyStack.length > SlidesEditor.MAX_HISTORY) {
            const excess = this._historyStack.length - SlidesEditor.MAX_HISTORY;
            this._historyStack = this._historyStack.slice(excess);
        }
        this._historyIndex = this._historyStack.length - 1;
        this._lastSaveOk = this._autosave();
    }

    /** Debounced push: groups rapid mutations (e.g. slider drags) into one undo snapshot */
    _pushDebounced() {
        clearTimeout(this._pushDebounceTimer);
        this._pushDebounceTimer = setTimeout(() => {
            this._pushDebounceTimer = null;
            this._push();
        }, SlidesEditor.PUSH_DEBOUNCE_MS);
    }

    undo() {
        // Flush pending debounced push before undoing
        if (this._pushDebounceTimer) {
            clearTimeout(this._pushDebounceTimer);
            this._pushDebounceTimer = null;
            this._push();
        }
        if (this._historyIndex <= 0) return;
        this._historyIndex--;
        this.data = JSON.parse(this._historyStack[this._historyIndex]);
        this._syncSelectionAfterDataChange();
        this.onUpdate('undo');
    }

    redo() {
        if (this._historyIndex >= this._historyStack.length - 1) return;
        this._historyIndex++;
        this.data = JSON.parse(this._historyStack[this._historyIndex]);
        this._syncSelectionAfterDataChange();
        this.onUpdate('redo');
    }

    get canUndo() { return this._historyIndex > 0; }
    get canRedo() { return this._historyIndex < this._historyStack.length - 1; }

    // ── Persistence ────────────────────────────────────────

    _computeWorkdocId(data) {
        const metaId = String(data?.metadata?.id || '').trim();
        if (metaId) return metaId.slice(0, 120);
        const title = String(data?.metadata?.title || 'sans-titre').toLowerCase();
        const slug = title
            .normalize('NFD')
            .replace(/[\u0300-\u036f]/g, '')
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-+|-+$/g, '')
            .slice(0, 80) || 'sans-titre';
        const slideCount = Array.isArray(data?.slides) ? data.slides.length : 0;
        return `${slug}-${slideCount}`;
    }

    _computeWorkdocHash(payload) {
        const raw = String(payload || '');
        let hash = 0;
        for (let i = 0; i < raw.length; i++) {
            hash = ((hash << 5) - hash + raw.charCodeAt(i)) | 0;
        }
        return Math.abs(hash).toString(36);
    }

    _updateWorkdocsIndex() {
        try {
            const payload = JSON.parse(JSON.stringify(this.data || {}));
            const now = Date.now();
            const id = this._computeWorkdocId(payload);
            const payloadText = JSON.stringify(payload);
            const payloadHash = this._computeWorkdocHash(payloadText);
            const raw = window.OEIStorage?.getRaw
                ? window.OEIStorage.getRaw(SlidesEditor.WORKDOCS_KEY)
                : localStorage.getItem(SlidesEditor.WORKDOCS_KEY);
            const list = raw ? JSON.parse(raw) : [];
            const safeList = Array.isArray(list) ? list : [];
            const previous = safeList.find(item => item && item.id === id) || null;
            const prevTimeline = Array.isArray(previous?.timeline)
                ? previous.timeline
                    .filter(item => item && typeof item === 'object')
                    .map(item => ({
                        ts: Number(item.ts) || 0,
                        hash: String(item.hash || ''),
                        title: String(item.title || ''),
                        slideCount: Number(item.slideCount) || 0,
                    }))
                    .filter(item => item.ts > 0)
                : [];
            const newest = prevTimeline[0] || null;
            const shouldAddSnapshot = !newest
                || newest.hash !== payloadHash
                || (now - Number(newest.ts || 0)) >= SlidesEditor.WORKDOC_TIMELINE_MIN_INTERVAL_MS;
            const timeline = (shouldAddSnapshot
                ? [{ ts: now, hash: payloadHash, title: String(payload?.metadata?.title || ''), slideCount: Array.isArray(payload?.slides) ? payload.slides.length : 0 }, ...prevTimeline]
                : prevTimeline)
                .slice(0, SlidesEditor.WORKDOC_TIMELINE_LIMIT);
            const entry = {
                id,
                title: String(payload?.metadata?.title || 'Présentation sans titre'),
                updatedAt: now,
                slideCount: Array.isArray(payload?.slides) ? payload.slides.length : 0,
                theme: (typeof payload?.theme === 'string' ? payload.theme : 'custom'),
                level: String(payload?.metadata?.level || '').trim(),
                institution: String(payload?.metadata?.institution || '').trim(),
                timeline,
                timelineCount: timeline.length,
                lastTimelineAt: timeline[0]?.ts || now,
                lastDataHash: payloadHash,
                data: payloadText,
            };
            const merged = [entry, ...safeList.filter(item => item && item.id !== id)]
                .slice(0, SlidesEditor.MAX_WORKDOCS);
            if (window.OEIStorage?.setRaw) window.OEIStorage.setRaw(SlidesEditor.WORKDOCS_KEY, JSON.stringify(merged));
            else localStorage.setItem(SlidesEditor.WORKDOCS_KEY, JSON.stringify(merged));
            return true;
        } catch (_) {
            return false;
        }
    }

    _maybeSaveRevisionSnapshot() {
        const now = Date.now();
        if (now - this._lastRevisionSnapshotAt < 90_000) return;
        if (typeof window.saveRevision !== 'function') return;
        this._lastRevisionSnapshotAt = now;
        try { window.saveRevision('auto'); } catch (_) {}
    }

    _autosave() {
        try {
            if (window.OEIStorage?.setJSON) window.OEIStorage.setJSON(SlidesEditor.STORAGE_KEY, this.data);
            else localStorage.setItem(SlidesEditor.STORAGE_KEY, JSON.stringify(this.data));
            this._updateWorkdocsIndex();
            this._maybeSaveRevisionSnapshot();
            return true;
        } catch(e) {
            console.error('[SlidesEditor] Autosave failed:', e.name, e.message);
            return false;
        }
    }

    loadDraft() {
        try {
            const raw = window.OEIStorage?.getRaw
                ? window.OEIStorage.getRaw(SlidesEditor.STORAGE_KEY)
                : localStorage.getItem(SlidesEditor.STORAGE_KEY);
            if (!raw) return false;
            this.load(JSON.parse(raw));
            return true;
        } catch(e) { return false; }
    }

    clearDraft() {
        if (window.OEIStorage?.remove) window.OEIStorage.remove(SlidesEditor.STORAGE_KEY);
        else localStorage.removeItem(SlidesEditor.STORAGE_KEY);
    }

    exportJson() {
        const data = JSON.parse(JSON.stringify(this.data));
        data.schemaVersion = Number.isFinite(Number(data.schemaVersion))
            ? Math.max(0, Math.trunc(Number(data.schemaVersion)))
            : SlidesEditor.CURRENT_SCHEMA_VERSION;
        data.metadata.modified = new Date().toISOString().slice(0, 10);
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        const name = (data.metadata.title || 'presentation').toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
        a.download = `${name}.json`;
        a.click();
        URL.revokeObjectURL(a.href);
    }

    importJson() {
        return new Promise((resolve, reject) => {
            const input = document.createElement('input');
            input.type = 'file'; input.accept = '.json';
            input.onchange = async e => {
                try {
                    const file = e.target.files?.[0];
                    if (!file) throw new Error('Aucun fichier sélectionné');
                    const text = await file.text();
                    if (window.OEIImportPipeline?.importFromText) {
                        const result = await window.OEIImportPipeline.importFromText(text, {
                            pipelineSettings: typeof window.getAIImportPipelineSettings === 'function'
                                ? window.getAIImportPipelineSettings()
                                : null,
                        });
                        const confirmed = await window.OEIImportPipeline.confirmImport(result, { sourceLabel: file.name });
                        if (!confirmed) {
                            const err = new Error('Import annulé');
                            err.code = window.OEIImportPipeline?.IMPORT_CANCELLED_CODE || 'OEI_IMPORT_CANCELLED';
                            throw err;
                        }
                        this.load(result.data);
                        resolve(result.data);
                        return;
                    }
                    const data = JSON.parse(_repairJsonText(text));
                    if (!Array.isArray(data.slides)) throw new Error('Format invalide : champ slides manquant');
                    this.load(data);
                    resolve(data);
                } catch(err) { reject(err); }
            };
            input.click();
        });
    }

    // ── Helpers for editor forms ──────────────────────────

    /**
     * Returns form field definitions for a given slide type.
     * Used by editor.html to build the properties panel.
     */
    static fieldsFor(type) {
        switch(type) {
            case 'title': return [
                { key: 'eyebrow',  label: 'Surtitre',     type: 'text',     placeholder: 'ex: Module 1' },
                { key: 'title',    label: 'Titre',         type: 'text',     required: true },
                { key: 'subtitle', label: 'Sous-titre',    type: 'text' },
                { key: 'author',   label: 'Auteur',        type: 'text' },
                { key: 'date',     label: 'Date',          type: 'text',     placeholder: 'ex: 2026-02' },
                { key: 'notes',    label: 'Notes orateur', type: 'textarea' },
            ];
            case 'chapter': return [
                { key: 'number',   label: 'Numéro',        type: 'text',     placeholder: 'ex: 1' },
                { key: 'title',    label: 'Titre',         type: 'text',     required: true },
                { key: 'subtitle', label: 'Sous-titre',    type: 'text' },
                { key: 'notes',    label: 'Notes orateur', type: 'textarea' },
            ];
            case 'bullets': return [
                { key: 'title',  label: 'Titre',         type: 'text', required: true },
                { key: 'items',  label: 'Points',        type: 'items' },
                { key: 'note',   label: 'Note encadrée', type: 'textarea', placeholder: 'Aparté affiché à droite...' },
                { key: 'notes',  label: 'Notes orateur', type: 'textarea' },
            ];
            case 'code': return [
                { key: 'title',       label: 'Titre',         type: 'text' },
                { key: 'language',    label: 'Langage',       type: 'select', options: ['python','javascript','yaml','bash','java','go','rust','sql','html','css','text'] },
                { key: 'code',        label: 'Code',          type: 'code' },
                { key: 'explanation', label: 'Explication',   type: 'textarea' },
                { key: 'notes',       label: 'Notes orateur', type: 'textarea' },
            ];
            case 'definition': return [
                { key: 'title',      label: 'Titre',         type: 'text' },
                { key: 'term',       label: 'Terme',         type: 'text', required: true },
                { key: 'definition', label: 'Définition',    type: 'textarea' },
                { key: 'example',    label: 'Exemple',       type: 'textarea' },
                { key: 'notes',      label: 'Notes orateur', type: 'textarea' },
            ];
            case 'comparison': return [
                { key: 'title',       label: 'Titre',           type: 'text' },
                { key: 'left.title',  label: 'Colonne gauche',  type: 'text' },
                { key: 'left.items',  label: 'Points gauche',   type: 'items' },
                { key: 'right.title', label: 'Colonne droite',  type: 'text' },
                { key: 'right.items', label: 'Points droite',   type: 'items' },
                { key: 'notes',       label: 'Notes orateur',   type: 'textarea' },
            ];
            case 'simulation': return [
                { key: 'title',  label: 'Titre',       type: 'text' },
                { key: 'widget', label: 'Widget',      type: 'widget-select' },
                { key: 'notes',  label: 'Notes orateur', type: 'textarea' },
            ];
            case 'image': return [
                { key: 'title',   label: 'Titre',       type: 'text' },
                { key: 'src',     label: 'URL image',   type: 'text', placeholder: '../images/...' },
                { key: 'caption', label: 'Légende',     type: 'text' },
                { key: 'notes',   label: 'Notes orateur', type: 'textarea' },
            ];
            case 'quote': return [
                { key: 'quote',  label: 'Citation',    type: 'textarea', required: true },
                { key: 'author', label: 'Auteur',      type: 'text' },
                { key: 'notes',  label: 'Notes orateur', type: 'textarea' },
            ];
            case 'split': return [
                { key: 'title',        label: 'Titre',              type: 'text' },
                { key: 'left.label',   label: 'Label gauche',       type: 'text' },
                { key: 'left.type',    label: 'Type gauche',        type: 'select', options: ['bullets','code','text'] },
                { key: 'left.items',   label: 'Points gauche',      type: 'items',  showIf: (s) => s.left?.type !== 'code' },
                { key: 'left.code',    label: 'Code gauche',        type: 'code',   showIf: (s) => s.left?.type === 'code' },
                { key: 'left.language',label: 'Langage gauche',     type: 'select', options: ['python','javascript','yaml','bash','text'], showIf: (s) => s.left?.type === 'code' },
                { key: 'right.label',  label: 'Label droite',       type: 'text' },
                { key: 'right.type',   label: 'Type droite',        type: 'select', options: ['bullets','code','text'] },
                { key: 'right.items',  label: 'Points droite',      type: 'items',  showIf: (s) => s.right?.type !== 'code' },
                { key: 'right.code',   label: 'Code droite',        type: 'code',   showIf: (s) => s.right?.type === 'code' },
                { key: 'right.language',label: 'Langage droite',    type: 'select', options: ['python','javascript','yaml','bash','text'], showIf: (s) => s.right?.type === 'code' },
                { key: 'notes',        label: 'Notes orateur',      type: 'textarea' },
            ];
            case 'blank': return [
                { key: 'html',  label: 'HTML libre', type: 'code' },
                { key: 'notes', label: 'Notes orateur', type: 'textarea' },
            ];
            case 'quiz': return [
                { key: 'title',       label: 'Question',       type: 'text', required: true },
                { key: 'quizType',    label: 'Type',           type: 'select', options: ['mcq', 'true-false', 'open'] },
                { key: 'options',     label: 'Réponses',       type: 'items' },
                { key: 'answer',      label: 'Bonne réponse (index 0-based ou texte)', type: 'text' },
                { key: 'explanation', label: 'Explication',    type: 'textarea' },
                { key: 'notes',       label: 'Notes orateur',  type: 'textarea' },
            ];
            case 'canvas': return []; // Canvas has its own element-level properties panel
            default: return [];
        }
    }

    /** Get nested value: getDeep(obj, 'left.title') */
    static getDeep(obj, path) {
        return path.split('.').reduce((o, k) => o?.[k], obj);
    }

    /** Set nested value: setDeep(obj, 'left.title', 'foo') */
    static setDeep(obj, path, value) {
        const keys = path.split('.');
        const last = keys.pop();
        const target = keys.reduce((o, k) => {
            if (o[k] == null) o[k] = {};
            return o[k];
        }, obj);
        target[last] = value;
    }
}

window.SlidesEditor = SlidesEditor;
